language: php

php:
  - 7.1

services:
  - redis-server

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - npm install

script:
  - npm run dev
  - vendor/bin/phpunit